### PR TITLE
Editing wgpu-rs post

### PR DESCRIPTION
**Pull request by unconed**
Explain some terms (hal), fill in some missing articles (the), make it clearer in the opening that the announcement is not about amethyst or rendy.

### CODE REVIEW

**Comment by Lokathor** [comment]
At the moment there's still a few more "the"s that are missing. I'm not sure if you mean it to be done yet or not.

**Comment by unconed** [comment]
I fixed some final typoes. cc @kvark

**Comment by kvark** [comment]
Bors r+

**Comment by grovesNL** [comment]
We don't have bors here :)

**Pull request merged**
